// Nigerian Administrative Hierarchy: State → LGA → Ward
// This is a representative dataset covering all 36 states + FCT
// with their major LGAs and wards

export interface NigeriaAdminHierarchy {
  [state: string]: {
    [lga: string]: string[];
  };
}

export const NIGERIA_ADMIN_DATA: NigeriaAdminHierarchy = {
  "Abia": {
    "Aba North": ["Ariaria", "Eziama", "Industrial", "Ogbor Hill", "Old GRA", "St. Eugene", "Umuola"],
    "Aba South": ["Aba River", "Abayi", "Enyimba", "Igwebuike", "Ngwa Road", "Obikabia", "Obuzor"],
    "Arochukwu": ["Arochukwu", "Atani", "Ihechiowa", "Isu", "Ndi Okoro"],
    "Bende": ["Bende", "Igbere", "Item", "Ozuitem", "Uturu"],
    "Ikwuano": ["Ariam", "Ibere", "Ikwuano", "Oloko", "Oboro"],
    "Isiala Ngwa North": ["Mbawsi", "Ngwa", "Ntigha", "Osusu", "Umuahia Road"],
    "Isiala Ngwa South": ["Okpuala Ngwa", "Omoba", "Ovungwu", "Obi Ngwa"],
    "Isuikwuato": ["Isuikwuato", "Nkwoagu", "Ovim", "Uturu"],
    "Obi Ngwa": ["Ahiaba", "Ihie", "Ngwa", "Obikabia", "Okpuala"],
    "Ohafia": ["Abiriba", "Amangwu", "Asaga", "Ebem", "Nkporo", "Ohafia"],
    "Osisioma": ["Aba", "Asa", "Osisioma", "Umuala"],
    "Ugwunagbo": ["Imo River", "Ndiakata", "Ugwunagbo"],
    "Ukwa East": ["Akwete", "Azumini", "Ndoki", "Obehie"],
    "Ukwa West": ["Asa", "Ohambele", "Owerrinta"],
    "Umuahia North": ["Afara", "Ibeku", "Ohuhu", "Old Umuahia", "Umuahia Urban"],
    "Umuahia South": ["Apumiri", "Nsulu", "Ubakala", "Umuahia South"],
    "Umu Nneochi": ["Eziachi", "Isuochi", "Ndi Oji", "Nneochi"]
  },
  "Adamawa": {
    "Demsa": ["Bille", "Demsa", "Dong", "Nassarawo"],
    "Fufore": ["Fufore", "Gurin", "Ribadu", "Yadim"],
    "Ganye": ["Ganye", "Gurum", "Sugu", "Toungo"],
    "Girei": ["Girei", "Dakri", "Modibbo", "Sangere"],
    "Gombi": ["Ga'anda", "Gombi North", "Gombi South", "Guyuk"],
    "Guyuk": ["Banjiram", "Chikila", "Dumna", "Guyuk"],
    "Hong": ["Garkida", "Hong", "Pella", "Uba"],
    "Jada": ["Ganye", "Jada", "Mbulo", "Toungo"],
    "Lamurde": ["Gyawana", "Lamurde", "Opalo", "Waduku"],
    "Madagali": ["Gulak", "Madagali", "Michika", "Shuwa"],
    "Maiha": ["Binyeri", "Maiha", "Sorau", "Pakka"],
    "Mayo Belwa": ["Bajama", "Gangfada", "Mayo Belwa", "Nassarawo"],
    "Michika": ["Bazza", "Kamale", "Michika", "Moda"],
    "Mubi North": ["Bahuli", "Kolere", "Mayo Bani", "Mubi", "Yelwa"],
    "Mubi South": ["Gella", "Lamorde", "Mujara", "Nassarawo"],
    "Numan": ["Bare", "Imburu", "Numan", "Sabon Pegi"],
    "Shelleng": ["Bobini", "Shelleng", "Tallum"],
    "Song": ["Dumne", "Gudu", "Song", "Zumo"],
    "Toungo": ["Kiri", "Toungo", "Yongra"],
    "Yola North": ["Alkalawa", "Doubeli", "Jimeta", "Karewa", "Limawa", "Luggere", "Nassarawo", "Rumde"],
    "Yola South": ["Adarawo", "Bole", "Makama", "Namtari", "Yolde Pate"]
  },
  "Akwa Ibom": {
    "Abak": ["Abak Urban", "Afaha Obong", "Ediene", "Midim", "Otoro"],
    "Eastern Obolo": ["Iko", "Okoroete", "Oron Road"],
    "Eket": ["Eket Urban", "Idua", "Okon"],
    "Esit Eket": ["Esit Eket", "Uquo"],
    "Essien Udim": ["Adiasim", "Afaha", "Ukana"],
    "Etim Ekpo": ["Etim Ekpo", "Utu"],
    "Etinan": ["Etinan", "Ndon Eyo", "Ikot Ebo"],
    "Ibeno": ["Ibeno", "Mkpanak"],
    "Ibesikpo Asutan": ["Ekom Iman", "Ikot Obioma", "Ibesikpo"],
    "Ibiono Ibom": ["Ibiono", "Ikot Ekang", "Nnung Udoe"],
    "Ika": ["Ika", "Urua Inyang"],
    "Ikono": ["Ikono", "Ibiaku", "Nnung Ndem"],
    "Ikot Abasi": ["Ikot Abasi", "Ikpa"],
    "Ikot Ekpene": ["Ikot Ekpene Urban", "Abia", "Ikono"],
    "Ini": ["Ikpe", "Ini", "Obotme"],
    "Itu": ["Ayadehe", "Itu", "Nkwo"],
    "Mbo": ["Effiat", "Mbo", "Enwang"],
    "Mkpat Enin": ["Mkpat Enin", "Ukpenekang"],
    "Nsit Atai": ["Nsit Atai", "Odot"],
    "Nsit Ibom": ["Afaha Nsit", "Nsit Ibom"],
    "Nsit Ubium": ["Ikot Edibon", "Nsit Ubium"],
    "Obot Akara": ["Nto Edino", "Obot Akara"],
    "Okobo": ["Okobo", "Okopedi"],
    "Onna": ["Onna", "Ikot Abasi"],
    "Oron": ["Oron Urban", "Udesi"],
    "Oruk Anam": ["Ikot Ibritam", "Ikot Okoro"],
    "Udung Uko": ["Udung Uko", "Eyofin"],
    "Ukanafun": ["Ikot Akpa Nkuk", "Ukanafun"],
    "Uruan": ["Idu", "Uruan", "Use Offot"],
    "Urue Offong Oruko": ["Urue Offong", "Oruko"],
    "Uyo": ["Etoi", "Ikono", "Ikot Ekpene Road", "Offot", "Uyo Urban", "Use Offot"]
  },
  "Anambra": {
    "Aguata": ["Achina", "Aguata", "Ekwulobia", "Nkpologwu", "Umuchu"],
    "Anambra East": ["Aguleri", "Nando", "Nsugbe", "Umuleri"],
    "Anambra West": ["Nzam", "Oroma Etiti", "Umueze Anam"],
    "Anaocha": ["Agulu", "Ichida", "Neni", "Nri"],
    "Awka North": ["Achalla", "Amansea", "Awba Ofemili", "Mgbakwu"],
    "Awka South": ["Amawbia", "Awka", "Isiagu", "Mbaukwu", "Nibo", "Nise", "Okpuno"],
    "Ayamelum": ["Anaku", "Ifite Ogwari", "Omasi", "Umueje"],
    "Dunukofia": ["Ifitedunu", "Nawgu", "Ukpo", "Umunnachi"],
    "Ekwusigo": ["Ihiala", "Ozubulu", "Oraifite"],
    "Idemili North": ["Abacha", "Nkpor", "Obosi", "Ogidi", "Oraukwu"],
    "Idemili South": ["Alor", "Awka-Etiti", "Nnobi", "Nnokwa", "Ojoto"],
    "Ihiala": ["Amorka", "Ihiala", "Mbosi", "Okija", "Orsumoghu", "Uli"],
    "Njikoka": ["Abagana", "Enugwu Agidi", "Enugwu Ukwu", "Nawfia", "Nimo"],
    "Nnewi North": ["Nnewi", "Otolo", "Umudim", "Uruagu"],
    "Nnewi South": ["Akwaihedi", "Amichi", "Ekwulumili", "Ezinifite", "Osumenyi", "Unubi"],
    "Ogbaru": ["Akili Ozizor", "Atani", "Ochuche", "Ogbaru", "Ohita"],
    "Onitsha North": ["American Quarter", "Awada", "GRA", "Inland Town", "Trans Nkisi"],
    "Onitsha South": ["Fegge", "Odoakpu", "Otu", "Woliwo"],
    "Orumba North": ["Ajalli", "Nanka", "Nawfija", "Ndikelionwu"],
    "Orumba South": ["Ezira", "Ihite", "Umunze", "Umuomaku"],
    "Oyi": ["Awkuzu", "Nkwelle Ezunaka", "Nteje", "Ogbunike", "Umunya"]
  },
  "Bauchi": {
    "Alkaleri": ["Alkaleri", "Futuk", "Maimadi"],
    "Bauchi": ["Bauchi Central", "Dan Iya", "Dan Kade", "Dawaki", "Fadaman Mada", "Hardo", "Makama", "Majidadi"],
    "Bogoro": ["Bogoro", "Lusa"],
    "Damban": ["Damban", "Jalam", "Katanga"],
    "Darazo": ["Darazo", "Gar", "Yali"],
    "Dass": ["Baraza", "Bundara", "Dass"],
    "Gamawa": ["Gamawa", "Gololo", "Udubo"],
    "Ganjuwa": ["Ganjuwa", "Kafin Madaki", "Miya"],
    "Giade": ["Dali", "Giade", "Zandi"],
    "Itas Gadau": ["Gadau", "Itas", "Madara"],
    "Jama'are": ["Jama'are", "Sambuwal"],
    "Katagum": ["Azare", "Katagum", "Madachi", "Zaki"],
    "Kirfi": ["Bula", "Kirfi", "Tafawa Balewa"],
    "Misau": ["Hardawa", "Misau", "Sade"],
    "Ningi": ["Burga", "Ningi", "Warji"],
    "Shira": ["Disina", "Shira", "Fakuwa"],
    "Tafawa Balewa": ["Bogoro", "Lere", "Tafawa Balewa"],
    "Toro": ["Jishi", "Lame", "Toro", "Zaranda"],
    "Warji": ["Katanga", "Sir", "Warji"],
    "Zaki": ["Katagum", "Sakwa", "Zaki"]
  },
  "Bayelsa": {
    "Brass": ["Brass", "Okpoama", "Twon"],
    "Ekeremor": ["Ekeremor", "Peremabiri", "Aleibiri"],
    "Kolokuma Opokuma": ["Igbedi", "Kaiama", "Odi"],
    "Nembe": ["Bassambiri", "Nembe", "Ogbolomabiri"],
    "Ogbia": ["Kolo", "Ogbia", "Oloibiri"],
    "Sagbama": ["Adagbabiri", "Sagbama", "Toru Ebeni"],
    "Southern Ijaw": ["Amassoma", "Oporoma", "Peretorugbene"],
    "Yenagoa": ["Agudama", "Biogbolo", "Kpansia", "Opolo", "Ovom", "Swali", "Yenagoa Central", "Yenizue Gene"]
  },
  "Benue": {
    "Ado": ["Ado", "Igumale", "Ulayi"],
    "Agatu": ["Agatu", "Obagaji", "Okokolo"],
    "Apa": ["Igata", "Offikpo", "Ugbokpo"],
    "Buruku": ["Binev", "Buruku", "Mbatyough"],
    "Gboko": ["Gboko Central", "Gboko North East", "Gboko North West", "Gboko South", "Yandev"],
    "Guma": ["Abinsi", "Gbajimba", "North Bank"],
    "Gwer East": ["Akpagher", "Aliade", "Ikpayongo"],
    "Gwer West": ["Ikpam", "Naka", "Tarkaa"],
    "Katsina-Ala": ["Ikurav Tiev", "Katsina-Ala", "Yooyo"],
    "Konshisha": ["Awajir", "Konshisha", "Tse-Agberagba"],
    "Kwande": ["Adikpo", "Kwande", "Turan"],
    "Logo": ["Logo", "Tombo", "Ugba"],
    "Makurdi": ["Agan", "Ankpa/Wadata", "Clerk Market", "Fiidi", "Modern Market", "North Bank", "Wadata"],
    "Obi": ["Awe", "Obarike", "Obi"],
    "Ogbadibo": ["Ai", "Otukpa", "Owukpa"],
    "Ohimini": ["Idekpa", "Ohimini", "Otukpo Road"],
    "Oju": ["Oju", "Orokam", "Ukpa"],
    "Okpokwu": ["Edumoga", "Okpoga", "Ugbokolo"],
    "Otukpo": ["Adoka", "Entekpa", "Otukpo Central", "Ugboju"],
    "Tarka": ["Gbor", "Tarka", "Wannune"],
    "Ukum": ["Korinya", "Zaki Biam"],
    "Ushongo": ["Lessel", "Tsar", "Ushongo"],
    "Vandeikya": ["Ihugh", "Tsar", "Vandeikya"]
  },
  "Borno": {
    "Abadam": ["Abadam", "Mallam Fatori"],
    "Askira Uba": ["Askira", "Lassa", "Uba"],
    "Bama": ["Bama", "Gulumba", "Soye"],
    "Bayo": ["Bayo", "Briyel", "Teli"],
    "Biu": ["Biu", "Dugja", "Gur", "Miringa"],
    "Chibok": ["Chibok", "Gatamarwa", "Shikarkir"],
    "Damboa": ["Alagarno", "Damboa", "Gumsuri"],
    "Dikwa": ["Dikwa", "Gajibo", "Sogoma"],
    "Gubio": ["Gubio", "Magumeri"],
    "Guzamala": ["Guzamala", "Gudumbali"],
    "Gwoza": ["Gwoza", "Limankara", "Ngoshe", "Pulka"],
    "Hawul": ["Hawul", "Kwaya Kusar", "Marama", "Shaffa"],
    "Jere": ["Dusuman", "Gongulong", "Jere", "Maimusari", "Old Maiduguri"],
    "Kaga": ["Benisheikh", "Kaga", "Mainok"],
    "Kala Balge": ["Kala", "Rann"],
    "Konduga": ["Dalori", "Konduga", "Kawuri"],
    "Kukawa": ["Baga", "Doro", "Kukawa"],
    "Kwaya Kusar": ["Biu", "Kurba", "Kwaya Kusar"],
    "Mafa": ["Mafa", "Mafa North"],
    "Magumeri": ["Magumeri"],
    "Maiduguri": ["Bolori I", "Bolori II", "Gamboru", "Gwange", "Hausari", "Lamisula", "Mafoni", "Maisandari", "Old Maiduguri", "Shehuri North", "Shehuri South"],
    "Marte": ["Kirenawa", "Marte"],
    "Mobbar": ["Damasak", "Mobbar"],
    "Monguno": ["Monguno"],
    "Ngala": ["Gambaru", "Ngala"],
    "Nganzai": ["Gajiram", "Nganzai"],
    "Shani": ["Buni Gari", "Garkida", "Shani"]
  },
  "Cross River": {
    "Abi": ["Abi", "Usumutong"],
    "Akamkpa": ["Akamkpa", "Mbarakom", "Oban"],
    "Akpabuyo": ["Akpabuyo", "Ikang"],
    "Bakassi": ["Archibong", "Bakassi"],
    "Bekwarra": ["Abuochiche", "Bekwarra"],
    "Biase": ["Adim", "Agwagune", "Biase"],
    "Boki": ["Boki", "Buanchor", "Obudu"],
    "Calabar Municipal": ["Akim", "Anantigha", "Calabar South", "Duke Town", "Henshaw Town", "Nassarawa"],
    "Calabar South": ["Calabar South", "Anantigha", "Ekpo Abasi", "Mbukpa"],
    "Etung": ["Etung", "Bendeghe"],
    "Ikom": ["Ikom", "Nde", "Nta"],
    "Obanliku": ["Becheve", "Obanliku"],
    "Obubra": ["Obubra", "Ofatura"],
    "Obudu": ["Obudu", "Utugwang"],
    "Odukpani": ["Odukpani", "Creek Town"],
    "Ogoja": ["Ogoja", "Mbube"],
    "Yakurr": ["Ugep", "Yakurr"]
  },
  "Delta": {
    "Aniocha North": ["Issele-Uku", "Onicha-Olona", "Onicha-Ugbo"],
    "Aniocha South": ["Agbor", "Nsukwa", "Owa"],
    "Bomadi": ["Bomadi", "Kpakiama"],
    "Burutu": ["Burutu", "Oboro-Otu"],
    "Ethiope East": ["Abraka", "Eku", "Sapele"],
    "Ethiope West": ["Jesse", "Oghara"],
    "Ika North East": ["Agbor", "Owa-Oyibu"],
    "Ika South": ["Agbor", "Abavo"],
    "Isoko North": ["Ozoro", "Ofagbe"],
    "Isoko South": ["Oleh", "Irri"],
    "Ndokwa East": ["Aboh", "Ashaka"],
    "Ndokwa West": ["Kwale", "Ogume"],
    "Okpe": ["Okpe", "Sapele"],
    "Oshimili North": ["Akwukwu-Igbo", "Ibusa"],
    "Oshimili South": ["Asaba", "Okwe"],
    "Patani": ["Patani", "Toru-Angiama"],
    "Sapele": ["Amukpe", "Sapele"],
    "Udu": ["Aladja", "Ovwian"],
    "Ughelli North": ["Agbarha", "Orogun", "Ughelli"],
    "Ughelli South": ["Effurun", "Otu-Jeremi"],
    "Ukwuani": ["Obiaruku", "Umutu"],
    "Uvwie": ["Effurun", "Ekpan", "Uvwie"],
    "Warri North": ["Koko", "Ogbe-Ijoh"],
    "Warri South": ["Warri Central", "Warri GRA", "Okumagba", "Pessu"],
    "Warri South West": ["Ogbe-Ijoh", "Ogidigben"]
  },
  "Ebonyi": {
    "Abakaliki": ["Azuiyiokwu", "Edda", "Kpirikpiri", "Nkaliki"],
    "Afikpo North": ["Afikpo", "Ozizza"],
    "Afikpo South": ["Edda", "Unwana"],
    "Ebonyi": ["Ebonyi", "Izzi"],
    "Ezza North": ["Ezzagu", "Onueke"],
    "Ezza South": ["Amasiri", "Ezza"],
    "Ikwo": ["Alike", "Ikwo", "Noyo"],
    "Ishielu": ["Azara", "Ezillo", "Ntezi"],
    "Ivo": ["Akaeze", "Ivo", "Ishiagu"],
    "Izzi": ["Iboko", "Izzi"],
    "Ohaozara": ["Okposi", "Uburu"],
    "Ohaukwu": ["Effium", "Ezzamgbo"],
    "Onicha": ["Abaomege", "Onicha"]
  },
  "Edo": {
    "Akoko-Edo": ["Igarra", "Okpella", "Ososo"],
    "Egor": ["Egor", "Ogbe", "Uselu"],
    "Esan Central": ["Irrua", "Uromi"],
    "Esan North East": ["Uromi", "Uzea"],
    "Esan South East": ["Ewohimi", "Ubiaja"],
    "Esan West": ["Ekpoma", "Iruekpen"],
    "Etsako Central": ["Fugar", "South Ibie"],
    "Etsako East": ["Agenebode", "Weppa"],
    "Etsako West": ["Auchi", "Jattu", "South Ibie"],
    "Igueben": ["Igueben", "Ekpon"],
    "Ikpoba Okha": ["Aduwawa", "Ikpoba Hill", "Okhoro"],
    "Oredo": ["Benin City", "GRA", "Ogbe", "Ring Road", "Sakponba"],
    "Orhionmwon": ["Abudu", "Ugo"],
    "Ovia North East": ["Okada", "Oluku"],
    "Ovia South West": ["Igbanke", "Iguobazuwa"],
    "Owan East": ["Afuze", "Otuo"],
    "Owan West": ["Ozalla", "Sabongida"],
    "Uhunmwonde": ["Ehor", "Uhunmwonde"]
  },
  "Ekiti": {
    "Ado Ekiti": ["Ado Central", "Oke Ila", "Oke Esa", "Dallimore"],
    "Efon": ["Efon Alaaye"],
    "Ekiti East": ["Aramoko", "Omuo"],
    "Ekiti South West": ["Ilawe", "Ogotun"],
    "Ekiti West": ["Aramoko", "Erijiyan"],
    "Emure": ["Emure", "Eporo"],
    "Gbonyin": ["Ode", "Aisegba"],
    "Ido Osi": ["Ifaki", "Ido", "Usi"],
    "Ijero": ["Ijero", "Iloro"],
    "Ikere": ["Ikere", "Ogbese"],
    "Ikole": ["Ikole", "Oye"],
    "Ilejemeje": ["Ilejemeje", "Iye"],
    "Irepodun Ifelodun": ["Igede", "Iyin", "Are"],
    "Ise Orun": ["Ise", "Orun"],
    "Moba": ["Otun", "Osan"],
    "Oye": ["Ayede", "Oye"]
  },
  "Enugu": {
    "Aninri": ["Aninri", "Nenwe", "Oduma"],
    "Awgu": ["Awgu", "Ituku", "Mgbowo"],
    "Enugu East": ["Abakpa Nike", "Emene", "Nike", "Trans-Ekulu"],
    "Enugu North": ["GRA", "New Haven", "Ogui Urban", "Asata"],
    "Enugu South": ["Achara Layout", "Awkunanaw", "Garki", "Maryland", "Uwani"],
    "Ezeagu": ["Aguobu", "Ezeagu", "Olo"],
    "Igbo Etiti": ["Diogbe", "Ogbede", "Ukehe"],
    "Igbo Eze North": ["Enugu-Ezike", "Ibagwa", "Ogrute"],
    "Igbo Eze South": ["Iheaka", "Itchi", "Ovoko"],
    "Isi Uzo": ["Eha Amufu", "Ikem", "Neke"],
    "Nkanu East": ["Agbani", "Amagunze", "Nkerefi"],
    "Nkanu West": ["Akegbe-Ugwu", "Ozalla"],
    "Nsukka": ["Nsukka Urban", "Obukpa", "Edem"],
    "Oji River": ["Inyi", "Oji", "Ugwuoba"],
    "Udenu": ["Obollo Afor", "Orba"],
    "Udi": ["Abor", "Ngwo", "Udi"],
    "Uzo Uwani": ["Adani", "Nimbo", "Ukpata"]
  },
  "FCT": {
    "AMAC": ["Garki", "City Centre", "Wuse", "Maitama", "Asokoro", "Gwarinpa", "Jabi", "Utako", "Gudu", "Durumi"],
    "Bwari": ["Bwari Central", "Kuduru", "Ushafa", "Dutse"],
    "Gwagwalada": ["Gwagwalada Central", "Kutunku", "Paiko"],
    "Kuje": ["Kuje Central", "Rubochi", "Chibiri"],
    "Kwali": ["Kwali Central", "Kilankwa", "Yangoji"],
    "Abaji": ["Abaji Central", "Yaba", "Gawu"]
  },
  "Gombe": {
    "Akko": ["Akko", "Kumo", "Pindiga"],
    "Balanga": ["Balanga", "Bambam", "Gelengu"],
    "Billiri": ["Billiri", "Tangale"],
    "Dukku": ["Dukku", "Jamari", "Zange"],
    "Funakaye": ["Ashaka", "Bajoga", "Funakaye"],
    "Gombe": ["Bolari", "Herwagana", "Jeka da Fari", "Nassarawo", "Pantami", "Shamaki"],
    "Kaltungo": ["Kaltungo", "Ture"],
    "Kwami": ["Bojude", "Kwami", "Malam Sidi"],
    "Nafada": ["Barunde", "Nafada"],
    "Shongom": ["Filiya", "Shongom"],
    "Yamaltu Deba": ["Deba", "Hinna", "Yamaltu"]
  },
  "Imo": {
    "Aboh Mbaise": ["Aboh", "Lorji", "Nguru"],
    "Ahiazu Mbaise": ["Ahiazu", "Ekwerazu", "Oru"],
    "Ehime Mbano": ["Ehime", "Umuezeala"],
    "Ezinihitte": ["Ezinihitte", "Itu", "Ife"],
    "Ideato North": ["Arondizuogu", "Urualla"],
    "Ideato South": ["Isiekenesi", "Ntu"],
    "Ihitte Uboma": ["Ihitte", "Uboma"],
    "Ikeduru": ["Iho", "Ikeduru"],
    "Isiala Mbano": ["Anara", "Isiala Mbano", "Umuelemai"],
    "Isu": ["Amandugba", "Isu"],
    "Mbaitoli": ["Mbieri", "Ogbaku"],
    "Ngor Okpala": ["Ngor", "Okpala"],
    "Njaba": ["Njaba", "Umuaka"],
    "Nkwerre": ["Nkwerre", "Amaigbo"],
    "Nwangele": ["Abba", "Nwangele"],
    "Obowo": ["Ehime", "Obowo"],
    "Oguta": ["Oguta", "Orsu"],
    "Ohaji Egbema": ["Mmahu", "Umuapu"],
    "Okigwe": ["Okigwe", "Umulolo"],
    "Orlu": ["Orlu", "Umuna"],
    "Orsu": ["Awo Idemili", "Orsu"],
    "Oru East": ["Omuma", "Oru East"],
    "Oru West": ["Mgbidi", "Oru West"],
    "Owerri Municipal": ["Owerri Urban", "Douglas", "Ikenegbu", "New Owerri"],
    "Owerri North": ["Emekuku", "Egbu", "Naze"],
    "Owerri West": ["Ihiagwa", "Nekede", "Obinze"]
  },
  "Jigawa": {
    "Auyo": ["Auyo", "Auyakagi"],
    "Babura": ["Babura", "Kanya"],
    "Biriniwa": ["Biriniwa", "Guri"],
    "Birnin Kudu": ["Birnin Kudu", "Kangire", "Kantoga"],
    "Buji": ["Buji", "Gantsa"],
    "Dutse": ["Dutse Central", "Kachi", "Sakwaya", "Takur"],
    "Gagarawa": ["Gagarawa", "Malam Madori"],
    "Garki": ["Garki", "Jigawa"],
    "Gumel": ["Gumel", "Gamsarka"],
    "Guri": ["Guri", "Margadu"],
    "Gwaram": ["Basirka", "Gwaram", "Fagam"],
    "Gwiwa": ["Gwiwa", "Kukayaure"],
    "Hadejia": ["Hadejia", "Matsaro"],
    "Jahun": ["Jahun", "Aujara"],
    "Kafin Hausa": ["Kafin Hausa", "Majia"],
    "Kaugama": ["Kaugama", "Birniwa"],
    "Kazaure": ["Kazaure", "Dabi"],
    "Kiri Kasamma": ["Kiri", "Kasamma"],
    "Kiyawa": ["Fagen", "Kiyawa"],
    "Maigatari": ["Maigatari", "Matamu"],
    "Malam Madori": ["Malam Madori"],
    "Miga": ["Miga", "Garko"],
    "Ringim": ["Ringim", "Sankara"],
    "Roni": ["Roni", "Yalo"],
    "Sule Tankarkar": ["Sule Tankarkar", "Takatsaba"],
    "Taura": ["Aujara", "Taura"],
    "Yankwashi": ["Gangara", "Yankwashi", "Ringim South"]
  },
  "Kaduna": {
    "Birnin Gwari": ["Birnin Gwari", "Randeggi"],
    "Chikun": ["Chikun", "Kakau", "Narayi", "Sabon Tasha", "Ungwar Rimi"],
    "Giwa": ["Galadima", "Giwa", "Kidandan"],
    "Igabi": ["Afaka", "Igabi", "Rigasa", "Turunku"],
    "Ikara": ["Ikara", "Kuya", "Saminaka"],
    "Jaba": ["Jaba", "Kwoi", "Nok"],
    "Jema'a": ["Godogodo", "Jema'a", "Kafanchan", "Kagoro"],
    "Kachia": ["Kachia", "Katari"],
    "Kaduna North": ["Badarawa", "Kabala", "Kawo", "Malali", "Unguwar Dosa", "Unguwar Rimi"],
    "Kaduna South": ["Barnawa", "Kakuri", "Kudenda", "Makera", "Television", "Tudun Wada"],
    "Kagarko": ["Kagarko", "Jere"],
    "Kajuru": ["Idon", "Kajuru", "Kufana"],
    "Kaura": ["Kaura", "Kagoro", "Manchok"],
    "Kauru": ["Kauru", "Pari"],
    "Kubau": ["Anchau", "Haskiya", "Kubau"],
    "Kudan": ["Hunkuyi", "Kudan", "Sabon Gari"],
    "Lere": ["Lere", "Saminaka"],
    "Makarfi": ["Makarfi", "Sabon Birni"],
    "Sabon Gari": ["Samaru", "Sabon Gari", "Zaria City"],
    "Sanga": ["Gwantu", "Sanga"],
    "Soba": ["Giwa", "Soba", "Maigana"],
    "Zangon Kataf": ["Atak", "Zangon Kataf", "Zonkwa"],
    "Zaria": ["Gyallesu", "Limanchin Kona", "Sabon Gari", "Tudun Wada", "Zaria City"]
  },
  "Kano": {
    "Ajingi": ["Ajingi", "Gama"],
    "Albasu": ["Albasu", "Fanda"],
    "Bagwai": ["Bagwai", "Gogel"],
    "Bebeji": ["Bebeji", "Durmawa"],
    "Bichi": ["Bichi", "Kyarama"],
    "Bunkure": ["Bunkure", "Kwanar Dawaki"],
    "Dala": ["Dala", "Gwale", "Koki", "Yakasai"],
    "Dambatta": ["Dambatta", "Jalli"],
    "Dawakin Kudu": ["Dawakin Kudu", "Gabasawa"],
    "Dawakin Tofa": ["Dawakin Tofa", "Rimingado"],
    "Doguwa": ["Doguwa", "Tudun Wada"],
    "Fagge": ["Fagge D1", "Fagge D2", "Sabon Gari"],
    "Gabasawa": ["Gabasawa", "Wudil"],
    "Garko": ["Garko", "Sumaila"],
    "Garun Mallam": ["Garun Mallam"],
    "Gaya": ["Gaya", "Wudil"],
    "Gezawa": ["Gezawa", "Jogana"],
    "Gwale": ["Dorayi", "Gwale", "Gyadi Gyadi", "Mandawari"],
    "Gwarzo": ["Getso", "Gwarzo"],
    "Kabo": ["Kabo", "Karaye"],
    "Kano Municipal": ["Dala", "Fagge", "Nassarawa", "Tarauni"],
    "Karaye": ["Karaye", "Rogo"],
    "Kibiya": ["Kibiya"],
    "Kiru": ["Bebeji", "Kiru"],
    "Kumbotso": ["Fan Road", "Kumbotso", "Panshekara"],
    "Kunchi": ["Kunchi", "Shanono"],
    "Kura": ["Karfi", "Kura"],
    "Madobi": ["Madobi"],
    "Makoda": ["Makoda"],
    "Minjibir": ["Minjibir", "Wasai"],
    "Nassarawa": ["Gwagwarwa", "Giginyu", "Nassarawa", "Unguwar Rimi"],
    "Rano": ["Kibiya", "Rano"],
    "Rimin Gado": ["Rimin Gado"],
    "Rogo": ["Rogo"],
    "Shanono": ["Shanono"],
    "Sumaila": ["Mekiya", "Sumaila"],
    "Takai": ["Takai"],
    "Tarauni": ["Tarauni", "Hotoro"],
    "Tofa": ["Tofa"],
    "Tsanyawa": ["Tsanyawa"],
    "Tudun Wada": ["Tudun Wada"],
    "Ungogo": ["Rangaza", "Ungogo", "Unguwar Gini"],
    "Warawa": ["Warawa"],
    "Wudil": ["Indabo", "Wudil"]
  },
  "Katsina": {
    "Bakori": ["Bakori", "Kabomo"],
    "Batagarawa": ["Batagarawa", "Makoda"],
    "Batsari": ["Batsari", "Jibia"],
    "Baure": ["Baure", "Babban Mutum"],
    "Bindawa": ["Bindawa", "Danja"],
    "Charanchi": ["Charanchi", "Kurfi"],
    "Dandume": ["Dandume", "Sabuwa"],
    "Danja": ["Danja", "Kafur"],
    "Dan Musa": ["Dan Musa", "Matazu"],
    "Daura": ["Daura", "Maiadua", "Sandamu"],
    "Dutsi": ["Dutsi", "Ingawa"],
    "Dutsin Ma": ["Dutsin Ma", "Kankia"],
    "Faskari": ["Dandume", "Faskari"],
    "Funtua": ["Funtua", "Dandume"],
    "Ingawa": ["Ingawa", "Kankara"],
    "Jibia": ["Jibia", "Batsari"],
    "Kafur": ["Kafur", "Danja"],
    "Kaita": ["Kaita", "Daura"],
    "Kankara": ["Kankara", "Faskari"],
    "Kankia": ["Kankia", "Kusada"],
    "Katsina": ["Katsina Central", "Kofar Kaura", "Kofar Marusa", "Shagari"],
    "Kurfi": ["Charanchi", "Kurfi"],
    "Kusada": ["Kankia", "Kusada"],
    "Mai'Adua": ["Daura", "Mai'Adua"],
    "Malumfashi": ["Kafur", "Malumfashi"],
    "Mani": ["Bindawa", "Mani"],
    "Mashi": ["Dutsi", "Mashi"],
    "Matazu": ["Dan Musa", "Matazu"],
    "Musawa": ["Matazu", "Musawa"],
    "Rimi": ["Charanchi", "Rimi"],
    "Sabuwa": ["Dandume", "Sabuwa"],
    "Safana": ["Batsari", "Safana"],
    "Sandamu": ["Daura", "Sandamu"],
    "Zango": ["Mai'Adua", "Zango"]
  },
  "Kebbi": {
    "Aleiro": ["Aleiro", "Dakingari"],
    "Arewa Dandi": ["Arewa", "Dandi"],
    "Argungu": ["Argungu", "Gulma"],
    "Augie": ["Augie", "Dandi"],
    "Bagudo": ["Bagudo", "Lolo"],
    "Birnin Kebbi": ["Ambursa", "Birnin Kebbi Central", "Gulumbe", "Kalgo"],
    "Bunza": ["Bunza", "Kangiwa"],
    "Dandi": ["Dandi", "Koko"],
    "Fakai": ["Fakai", "Mahuta"],
    "Gwandu": ["Besse", "Gwandu"],
    "Jega": ["Jega", "Aliero"],
    "Kalgo": ["Birnin Kebbi", "Kalgo"],
    "Koko Besse": ["Besse", "Koko"],
    "Maiyama": ["Maiyama", "Zuru"],
    "Ngaski": ["Ngaski", "Wara"],
    "Sakaba": ["Sakaba", "Wasagu"],
    "Shanga": ["Shanga", "Yelwa"],
    "Suru": ["Dakingari", "Suru"],
    "Wasagu Danko": ["Danko", "Wasagu"],
    "Yauri": ["Gungu", "Yauri"],
    "Zuru": ["Dabai", "Zuru"]
  },
  "Kogi": {
    "Adavi": ["Adavi", "Ogaminana"],
    "Ajaokuta": ["Ajaokuta", "Ebiya"],
    "Ankpa": ["Ankpa", "Enjema"],
    "Bassa": ["Bassa", "Oguma"],
    "Dekina": ["Anyigba", "Dekina"],
    "Ibaji": ["Ibaji", "Onyedega"],
    "Idah": ["Idah", "Igalamela"],
    "Igalamela Odolu": ["Odolu", "Igalamela"],
    "Ijumu": ["Iffe", "Ijumu"],
    "Kabba Bunu": ["Kabba", "Bunu"],
    "Koton Karfe": ["Koton Karfe", "Lokoja"],
    "Lokoja": ["Felele", "Lokoja Central", "Adankolo", "Kabawa"],
    "Mopa Muro": ["Mopa", "Muro"],
    "Ofu": ["Ofu", "Itobe"],
    "Ogori Magongo": ["Ogori", "Magongo"],
    "Okehi": ["Okehi", "Osara"],
    "Okene": ["Okene Central", "Okene South"],
    "Olamaboro": ["Olamaboro", "Imane"],
    "Omala": ["Abejukolo", "Omala"],
    "Yagba East": ["Egbe", "Isanlu"],
    "Yagba West": ["Odo Ere", "Ponyan"]
  },
  "Kwara": {
    "Asa": ["Afon", "Asa", "Owode"],
    "Baruten": ["Kosubosu", "Okuta"],
    "Edu": ["Lafiagi", "Patigi"],
    "Ekiti": ["Araromi", "Eruku"],
    "Ifelodun": ["Idofin", "Share"],
    "Ilorin East": ["Alore", "Gambari", "Oke Oyi"],
    "Ilorin South": ["Alagbado", "Fufu", "Idi Ape"],
    "Ilorin West": ["Adewole", "Baboko", "Fate", "GRA", "Oloje"],
    "Irepodun": ["Ajase", "Omu-Aran"],
    "Isin": ["Igbaja", "Owu"],
    "Kaiama": ["Kaiama", "Kemanji"],
    "Moro": ["Bode Saadu", "Jebba", "Malete"],
    "Offa": ["Igbona", "Offa"],
    "Oke Ero": ["Ekan", "Omu"],
    "Oyun": ["Ijagbo", "Ilemona"],
    "Patigi": ["Lade", "Patigi"]
  },
  "Lagos": {
    "Agege": ["Agege", "Dopemu", "Orile Agege"],
    "Ajeromi-Ifelodun": ["Ajeromi", "Ifelodun", "Layeni"],
    "Alimosho": ["Akowonjo", "Egbeda", "Idimu", "Ijegun", "Ikotun"],
    "Amuwo-Odofin": ["Amuwo", "Festac", "Mile 2", "Satellite"],
    "Apapa": ["Apapa", "Ajegunle", "GRA"],
    "Badagry": ["Ajara", "Badagry", "Topo"],
    "Epe": ["Epe", "Ibeju", "Noforija"],
    "Eti-Osa": ["Ajah", "Ikoyi", "Lekki", "Victoria Island"],
    "Ibeju-Lekki": ["Awoyaya", "Ibeju", "Lekki"],
    "Ifako-Ijaiye": ["Ifako", "Ijaiye", "Ogba"],
    "Ikeja": ["Alausa", "Allen", "GRA", "Ikeja", "Oregun"],
    "Ikorodu": ["Ikorodu", "Igbogbo", "Bayeku"],
    "Kosofe": ["Ketu", "Ogudu", "Ojota"],
    "Lagos Island": ["Isale Eko", "Lagos Island", "Onikan"],
    "Lagos Mainland": ["Ebute Metta", "Surulere", "Yaba"],
    "Mushin": ["Idi Araba", "Mushin", "Oshodi"],
    "Ojo": ["Iba", "Ojo", "Igando"],
    "Oshodi-Isolo": ["Isolo", "Mafoluku", "Oshodi"],
    "Shomolu": ["Bariga", "Gbagada", "Shomolu"],
    "Surulere": ["Aguda", "Iponri", "Surulere"]
  },
  "Nasarawa": {
    "Akwanga": ["Akwanga", "Andaha", "Wamba"],
    "Awe": ["Awe", "Azara", "Ribi"],
    "Doma": ["Doma", "Agbashi"],
    "Karu": ["Karu", "Jikwoyi", "Nyanya"],
    "Keana": ["Giza", "Keana"],
    "Keffi": ["Angwan Toni", "Keffi", "Keffi West"],
    "Kokona": ["Agwada", "Garaku"],
    "Lafia": ["Chiroma", "Doma Road", "Lafia Central", "Makurdi Road", "Shabu"],
    "Nassarawa": ["Nassarawa Central", "Udege"],
    "Nassarawa Eggon": ["Agyaragu", "Nassarawa Eggon"],
    "Obi": ["Awe", "Obi"],
    "Toto": ["Gadabuke", "Toto"],
    "Wamba": ["Kwarra", "Wamba"]
  },
  "Niger": {
    "Agaie": ["Agaie", "Baro"],
    "Agwara": ["Agwara", "Rofia"],
    "Bida": ["Bida Central", "Bida North", "Bida South", "Dokodza"],
    "Borgu": ["Babanna", "Kaoji", "New Bussa", "Wawa"],
    "Bosso": ["Bosso", "Maikunkele"],
    "Chanchaga": ["Chanchaga", "Limawa", "Minna Central", "Tunga"],
    "Edatti": ["Edatti", "Kutigi"],
    "Gbako": ["Gbako", "Lemu"],
    "Gurara": ["Gawu", "Izom"],
    "Katcha": ["Badeggi", "Katcha"],
    "Kontagora": ["Kontagora Central", "Magama", "Ushe"],
    "Lapai": ["Gulu", "Lapai"],
    "Lavun": ["Doko", "Jima", "Kutigi"],
    "Magama": ["Auna", "Magama", "Nasko"],
    "Mariga": ["Bangi", "Mariga"],
    "Mashegu": ["Ibbi", "Mashegu"],
    "Mokwa": ["Jebba", "Mokwa", "Rabba"],
    "Munya": ["Minna", "Sarkin Pawa"],
    "Paikoro": ["Gwada", "Paikoro"],
    "Rafi": ["Kagara", "Rafi"],
    "Rijau": ["Rijau", "Duku"],
    "Shiroro": ["Kuta", "Shiroro"],
    "Suleja": ["Bagama", "Madalla", "Suleja"],
    "Tafa": ["Tafa", "Wuse"],
    "Wushishi": ["Wushishi", "Zungeru"]
  },
  "Ogun": {
    "Abeokuta North": ["Ake", "Ibara", "Olumo", "Sapon"],
    "Abeokuta South": ["Ake", "Igbein", "Ijemo", "Itoku", "Kuto"],
    "Ado-Odo Ota": ["Ado Odo", "Igbesa", "Ota", "Sango"],
    "Ewekoro": ["Arigbajo", "Ewekoro", "Papalanto"],
    "Ifo": ["Ifo", "Ojodu", "Pakoto"],
    "Ijebu East": ["Ijebu Ife", "Ogbere"],
    "Ijebu North": ["Ago Iwoye", "Ijebu Igbo", "Oru"],
    "Ijebu North East": ["Atan", "Ijebu North East"],
    "Ijebu Ode": ["Ijebu Ode", "Ijasi", "Itoro"],
    "Ikenne": ["Ikenne", "Iperu", "Ilishan"],
    "Imeko Afon": ["Afon", "Imeko"],
    "Ipokia": ["Idiroko", "Ipokia"],
    "Obafemi Owode": ["Mowe", "Ofada", "Owode"],
    "Odeda": ["Abeokuta North", "Odeda"],
    "Odogbolu": ["Odogbolu", "Ikenne"],
    "Ogun Waterside": ["Abigi", "Iwopin"],
    "Remo North": ["Ilara", "Isara"],
    "Sagamu": ["Ijoku", "Sagamu"],
    "Yewa North": ["Aiyetoro", "Sawonjo"],
    "Yewa South": ["Ilaro", "Owode"]
  },
  "Ondo": {
    "Akoko North East": ["Ikare", "Arigidi"],
    "Akoko North West": ["Auga", "Oka"],
    "Akoko South East": ["Isua", "Supare"],
    "Akoko South West": ["Oka", "Ose"],
    "Akure North": ["Iju", "Itaogbolu"],
    "Akure South": ["Alagbaka", "Isinkan", "Oba Ile", "Oke Aro", "Shagari"],
    "Ese Odo": ["Igbekebo", "Sabomi"],
    "Idanre": ["Idanre", "Owena"],
    "Ifedore": ["Igbara Oke", "Igbara Odo"],
    "Ilaje": ["Igbokoda", "Ugbo"],
    "Ile Oluji Okeigbo": ["Ile Oluji", "Okeigbo"],
    "Irele": ["Irele", "Ode Irele"],
    "Odigbo": ["Agbabu", "Ore"],
    "Okitipupa": ["Okitipupa", "Erinje"],
    "Ondo East": ["Bolorunduro", "Ondo East"],
    "Ondo West": ["Ondo Central", "Sabo"],
    "Ose": ["Ifon", "Ose"],
    "Owo": ["Idasen", "Owo"]
  },
  "Osun": {
    "Aiyedade": ["Gbongan", "Odeomu"],
    "Aiyedire": ["Ile Ogbo", "Ode Omu"],
    "Atakunmosa East": ["Ilesa East", "Iperindo"],
    "Atakunmosa West": ["Ilesa West", "Osu"],
    "Boluwaduro": ["Otan Ayegbaju", "Ila"],
    "Boripe": ["Iragbiji", "Iree"],
    "Ede North": ["Ede North", "Sekona"],
    "Ede South": ["Ede South", "Alusekere"],
    "Egbedore": ["Awo", "Ido Osun"],
    "Ejigbo": ["Ejigbo", "Masifa"],
    "Ife Central": ["Ile Ife", "Moore", "Ilode"],
    "Ife East": ["Ife East", "Modakeke"],
    "Ife North": ["Edunabon", "Ipetumodu"],
    "Ife South": ["Ifetedo", "Ife South"],
    "Ifedayo": ["Oke Ila", "Ora"],
    "Ifelodun": ["Ikirun", "Ororuwo"],
    "Ila": ["Ila Orangun", "Oke Ila"],
    "Ilesa East": ["Ilesa", "Ijesha"],
    "Ilesa West": ["Ereja", "Ilesa West"],
    "Irepodun": ["Ikirun", "Ilobu"],
    "Irewole": ["Ikire", "Ikoyi"],
    "Isokan": ["Apomu", "Ikoyi"],
    "Iwo": ["Iwo", "Isale Oba"],
    "Obokun": ["Ibokun", "Ilare"],
    "Odo Otin": ["Inisa", "Okuku"],
    "Ola Oluwa": ["Bode Osi", "Ola Oluwa"],
    "Olorunda": ["Igbona", "Oke Baale", "Osogbo East"],
    "Oriade": ["Ijebu Jesa", "Ikeji Ile"],
    "Orolu": ["Ifon Osun", "Orolu"],
    "Osogbo": ["Aiyekale", "Alekuwodo", "Isale Osun", "Oke Baale", "Ota Efun"]
  },
  "Oyo": {
    "Afijio": ["Fiditi", "Jobele"],
    "Akinyele": ["Akobo", "Moniya", "Ojoo"],
    "Atiba": ["Atiba", "Oyo East"],
    "Atisbo": ["Ago Are", "Tede"],
    "Egbeda": ["Egbeda", "Olunde"],
    "Ibadan North": ["Agodi Gate", "Bodija", "Sango", "University of Ibadan"],
    "Ibadan North East": ["Iwo Road", "Mapo"],
    "Ibadan North West": ["Eleyele", "Oke Are"],
    "Ibadan South East": ["Mapo", "Orita Aperin"],
    "Ibadan South West": ["Oke Ado", "Ring Road"],
    "Ibarapa Central": ["Igboora", "Idere"],
    "Ibarapa East": ["Eruwa", "Lanlate"],
    "Ibarapa North": ["Ayete", "Tapa"],
    "Ido": ["Ido", "Apata"],
    "Irepo": ["Irepo", "Kishi"],
    "Iseyin": ["Iseyin", "Ado Awaye"],
    "Itesiwaju": ["Komu", "Otu"],
    "Iwajowa": ["Ayegun", "Iwere Ile"],
    "Kajola": ["Kajola", "Okeho"],
    "Lagelu": ["Iyanganku", "Lagelu"],
    "Ogbomosho North": ["Aaje", "Ogbomosho Central", "Sabo"],
    "Ogbomosho South": ["Arowomole", "Ogbomosho South"],
    "Ogo Oluwa": ["Ajaawa", "Ogo Oluwa"],
    "Oluyole": ["Oluyole", "Ring Road"],
    "Ona Ara": ["Akanran", "Olodo"],
    "Oorelope": ["Igboho", "Oorelope"],
    "Ori Ire": ["Ikoyi", "Oyo West"],
    "Oyo East": ["Kosobo", "Oyo East"],
    "Oyo West": ["Oyo West", "Ojongbodu"],
    "Saki East": ["Ago Amodu", "Ogboro"],
    "Saki West": ["Isale Oyo", "Saki"],
    "Surulere": ["Gambari", "Iresa Adu"]
  },
  "Plateau": {
    "Barkin Ladi": ["Barkin Ladi", "Gwash", "Heipang"],
    "Bassa": ["Bassa", "Jebbu", "Miango"],
    "Bokkos": ["Bokkos", "Daffo", "Mushere"],
    "Jos East": ["Fobur", "Jarawa", "Shere"],
    "Jos North": ["Abattoir", "Angwan Rogo", "Gangare", "Hwolshe", "Jos", "Naraguta", "Tafawa Balewa"],
    "Jos South": ["Bukuru", "Du", "Gyel", "Kuru", "Rayfield", "Zawan"],
    "Kanam": ["Dengi", "Kanam"],
    "Kanke": ["Amper", "Kanke"],
    "Langtang North": ["Langtang", "Panyam"],
    "Langtang South": ["Mabudi", "Shendam"],
    "Mangu": ["Gindiri", "Kerang", "Mangu"],
    "Mikang": ["Lalin", "Mikang"],
    "Pankshin": ["Kanke", "Pankshin"],
    "Qua'an Pan": ["Namu", "Shendam"],
    "Riyom": ["Riyom", "Wereng"],
    "Shendam": ["Shendam", "Yelwa"],
    "Wase": ["Bashar", "Wase"]
  },
  "Rivers": {
    "Abua Odual": ["Abua", "Odual"],
    "Ahoada East": ["Ahoada", "Edeoha"],
    "Ahoada West": ["Akinima", "Engenni"],
    "Akuku-Toru": ["Abonnema", "Buguma"],
    "Andoni": ["Ngo", "Unyeada"],
    "Asari-Toru": ["Buguma", "Ido"],
    "Bonny": ["Bonny", "Finima"],
    "Degema": ["Degema", "Usokun"],
    "Eleme": ["Alode", "Ebubu", "Ogale"],
    "Emohua": ["Emohua", "Rumuji"],
    "Etche": ["Edegelem", "Okehi"],
    "Gokana": ["Bori", "Kpor"],
    "Ikwerre": ["Isiokpo", "Ozuoba", "Ubima"],
    "Khana": ["Bane", "Bori"],
    "Obio-Akpor": ["Choba", "Rumuigbo", "Rumuokwurushi", "Rumuolumeni", "Rumuokoro"],
    "Ogba-Egbema-Ndoni": ["Erema", "Omoku"],
    "Ogu-Bolo": ["Ogu", "Bolo"],
    "Okrika": ["Okrika", "Ogoloma"],
    "Omuma": ["Omuma", "Umuechem"],
    "Opobo-Nkoro": ["Nkoro", "Opobo"],
    "Oyigbo": ["Afam", "Oyigbo"],
    "Port Harcourt": ["Diobu", "GRA", "Mile 1", "Mile 3", "Old Township", "Rumuola", "Trans Amadi"],
    "Tai": ["Kpite", "Tai"]
  },
  "Sokoto": {
    "Binji": ["Binji", "Silame"],
    "Bodinga": ["Bodinga", "Dange"],
    "Dange Shuni": ["Dange", "Shuni"],
    "Gada": ["Gada", "Goronyo"],
    "Goronyo": ["Goronyo", "Gatawa"],
    "Gudu": ["Gudu", "Isa"],
    "Gwadabawa": ["Chimola", "Gwadabawa"],
    "Illela": ["Illela", "Araba"],
    "Isa": ["Gidan Madi", "Isa"],
    "Kware": ["Kware", "Kalambaina"],
    "Kebbe": ["Kebbe", "Tambuwal"],
    "Rabah": ["Rabah", "Wurno"],
    "Sabon Birni": ["Sabon Birni", "Isah"],
    "Shagari": ["Shagari", "Yabo"],
    "Silame": ["Binji", "Silame"],
    "Sokoto North": ["Arkilla", "Gawon Nama", "Marina", "Sokoto"],
    "Sokoto South": ["Gagi", "Mabera", "Tudun Wada"],
    "Tambuwal": ["Bakura", "Tambuwal"],
    "Tangaza": ["Tangaza", "Gudu"],
    "Tureta": ["Tureta", "Achida"],
    "Wamako": ["Gidan Igwai", "Wamako", "Wammako"],
    "Wurno": ["Achida", "Wurno"],
    "Yabo": ["Shagari", "Yabo"]
  },
  "Taraba": {
    "Ardo Kola": ["Ardo Kola", "Sunkani"],
    "Bali": ["Bali", "Maihula"],
    "Donga": ["Donga", "Suntai"],
    "Gashaka": ["Gembu", "Serti"],
    "Gassol": ["Gassol", "Mutum Biyu"],
    "Ibi": ["Ibi", "Sarkin Kudu"],
    "Jalingo": ["Barade", "Jalingo Central", "Kona", "Majidadi", "Nassarawo"],
    "Karim Lamido": ["Karim", "Lamido", "Jen"],
    "Kurmi": ["Baissa", "Kurmi"],
    "Lau": ["Lau", "Abong"],
    "Sardauna": ["Gembu", "Mayo Selbe"],
    "Takum": ["Takum", "Chanchanji"],
    "Ussa": ["Lissam", "Ussa"],
    "Wukari": ["Hospital", "Puje", "Wukari"],
    "Yorro": ["Yorro", "Pantisawa"],
    "Zing": ["Monkin", "Zing"]
  },
  "Yobe": {
    "Bade": ["Dagona", "Gashua"],
    "Bursari": ["Bursari", "Dapchi"],
    "Damaturu": ["Bindigari", "Damaturu Central", "Kalallawa", "Nayinawa", "Pompomari"],
    "Fika": ["Daya", "Fika", "Ngalda"],
    "Fune": ["Damagum", "Fune", "Jajimaji"],
    "Geidam": ["Geidam", "Kanama"],
    "Gujba": ["Buni Yadi", "Gujba"],
    "Gulani": ["Bara", "Gulani"],
    "Jakusko": ["Jakusko", "Kanamma"],
    "Karasuwa": ["Jajere", "Karasuwa"],
    "Machina": ["Machina", "Yusufari"],
    "Nangere": ["Jaji Maji", "Nangere"],
    "Nguru": ["Bulanguwa", "Nguru Central", "Nguru East"],
    "Potiskum": ["Mamudo", "Potiskum Central", "Yerimaram"],
    "Tarmuwa": ["Babban Gida", "Tarmuwa"],
    "Yunusari": ["Kanamma", "Yunusari"],
    "Yusufari": ["Machina", "Yusufari"]
  },
  "Zamfara": {
    "Anka": ["Anka", "Bagega"],
    "Bakura": ["Bakura", "Rawayya"],
    "Birnin Magaji Kiyaw": ["Birnin Magaji", "Kiyawa"],
    "Bukkuyum": ["Bukkuyum", "Nasarawa"],
    "Bungudu": ["Bungudu", "Samaru"],
    "Gummi": ["Gummi", "Moriki"],
    "Gusau": ["Gusau Central", "Mada", "Samaru", "Tudun Wada", "Unguwar Dalhatu"],
    "Kaura Namoda": ["Kaura Namoda", "Moriki"],
    "Maradun": ["Maradun", "Ruwan Bore"],
    "Maru": ["Dan Sadau", "Maru"],
    "Shinkafi": ["Kware", "Shinkafi"],
    "Talata Mafara": ["Talata Mafara", "Tunfafi"],
    "Tsafe": ["Tsafe", "Yandoto"],
    "Zurmi": ["Kanoma", "Zurmi"]
  }
};

export const getAllStates = (): string[] => Object.keys(NIGERIA_ADMIN_DATA).sort();

export const getLGAsForState = (state: string): string[] => {
  const stateData = NIGERIA_ADMIN_DATA[state];
  return stateData ? Object.keys(stateData).sort() : [];
};

export const getWardsForLGA = (state: string, lga: string): string[] => {
  const stateData = NIGERIA_ADMIN_DATA[state];
  if (!stateData) return [];
  const lgaData = stateData[lga];
  return lgaData ? [...lgaData].sort() : [];
};
