project_id = "vhuixgcjmrmfowzrulac"

[functions.sync-google-sheets]
verify_jwt = true

[functions.check-follow-up-reminders]
verify_jwt = false

[functions.resolve-looker-url]
verify_jwt = false

[functions.data-quality-check]
verify_jwt = false
