/**
 * Automated document generation for Amehnities AI.
 *
 * The model replies in structured Markdown; this module turns that reply into
 * a real deliverable — Word (.docx), PowerPoint (.pptx), PDF or Excel — using
 * the libraries already bundled with the app. Nothing leaves the browser.
 */

export type DocFormat = "docx" | "pptx" | "pdf" | "xlsx";

export interface DocSection {
  heading: string;
  level: number;
  paragraphs: string[];
  bullets: string[];
  tables: { headers: string[]; rows: string[][] }[];
}

export interface ParsedDoc {
  title: string;
  sections: DocSection[];
}

const BRAND = { primary: "1E3A8A", accent: "0EA5E9", ink: "0F172A", muted: "475569" };

const stripMd = (s: string) =>
  s.replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`(.+?)`/g, "$1")
    .replace(/\[(.+?)\]\(.*?\)/g, "$1")
    .trim();

/** Parse an assistant Markdown answer into headings, prose, bullets and tables. */
export function parseMarkdownDocument(markdown: string, fallbackTitle = "Amehnities AI Report"): ParsedDoc {
  const lines = markdown.replace(/\r/g, "").split("\n");
  const sections: DocSection[] = [];
  let title = "";
  let current: DocSection | null = null;

  const push = () => { if (current) sections.push(current); };
  const ensure = () => {
    if (!current) current = { heading: "Overview", level: 2, paragraphs: [], bullets: [], tables: [] };
    return current;
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (/^FOLLOWUPS:/i.test(trimmed)) continue;

    const heading = /^(#{1,4})\s+(.*)$/.exec(trimmed);
    if (heading) {
      const level = heading[1].length;
      const text = stripMd(heading[2]);
      if (level === 1 && !title) { title = text; continue; }
      push();
      current = { heading: text, level, paragraphs: [], bullets: [], tables: [] };
      continue;
    }

    // Markdown table
    if (trimmed.startsWith("|") && /\|/.test(lines[i + 1] ?? "") && /^\s*\|?[\s:|-]+\|?\s*$/.test(lines[i + 1] ?? "")) {
      const headers = splitRow(trimmed);
      const rows: string[][] = [];
      i += 2;
      while (i < lines.length && lines[i].trim().startsWith("|")) {
        rows.push(splitRow(lines[i].trim()));
        i++;
      }
      i--;
      ensure().tables.push({ headers, rows });
      continue;
    }

    if (/^[-*•]\s+/.test(trimmed) || /^\d+[.)]\s+/.test(trimmed)) {
      ensure().bullets.push(stripMd(trimmed.replace(/^[-*•]\s+/, "").replace(/^\d+[.)]\s+/, "")));
      continue;
    }

    ensure().paragraphs.push(stripMd(trimmed));
  }
  push();

  return { title: title || fallbackTitle, sections: sections.length ? sections : [{ heading: "Summary", level: 2, paragraphs: [stripMd(markdown)], bullets: [], tables: [] }] };
}

const splitRow = (line: string) =>
  line.replace(/^\|/, "").replace(/\|$/, "").split("|").map((c) => stripMd(c));

const download = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
};

const safeName = (title: string, ext: string) =>
  `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "amehnities-report"}.${ext}`;

// ------------------------------------------------------------------ DOCX
async function buildDocx(doc: ParsedDoc) {
  const { Document, Packer, Paragraph, HeadingLevel, TextRun, Table, TableRow, TableCell, WidthType, AlignmentType } =
    await import("docx");

  const children: unknown[] = [
    new Paragraph({ text: doc.title, heading: HeadingLevel.TITLE }),
    new Paragraph({
      children: [new TextRun({ text: `Generated by Amehnities AI · ${new Date().toLocaleString()}`, italics: true, color: BRAND.muted })],
    }),
  ];

  for (const s of doc.sections) {
    children.push(new Paragraph({
      text: s.heading,
      heading: s.level <= 2 ? HeadingLevel.HEADING_1 : s.level === 3 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
    }));
    s.paragraphs.forEach((p) => children.push(new Paragraph({ text: p, spacing: { after: 120 } })));
    s.bullets.forEach((b) => children.push(new Paragraph({ text: b, bullet: { level: 0 } })));
    for (const t of s.tables) {
      children.push(new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            children: t.headers.map((h) => new TableCell({
              shading: { fill: BRAND.primary },
              children: [new Paragraph({ alignment: AlignmentType.LEFT, children: [new TextRun({ text: h, bold: true, color: "FFFFFF" })] })],
            })),
          }),
          ...t.rows.map((r) => new TableRow({
            children: t.headers.map((_, ci) => new TableCell({ children: [new Paragraph(r[ci] ?? "")] })),
          })),
        ],
      }));
      children.push(new Paragraph({ text: "" }));
    }
  }

  const document = new Document({ sections: [{ properties: {}, children: children as never[] }] });
  return Packer.toBlob(document);
}

// ------------------------------------------------------------------ PPTX
async function buildPptx(doc: ParsedDoc) {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";

  const cover = pptx.addSlide();
  cover.background = { color: BRAND.primary };
  cover.addText(doc.title, { x: 0.6, y: 2.0, w: 8.8, h: 1.4, fontSize: 34, bold: true, color: "FFFFFF" });
  cover.addText(`Amehnities AI · ${new Date().toLocaleDateString()}`, { x: 0.6, y: 3.5, fontSize: 14, color: "BFDBFE" });

  for (const s of doc.sections) {
    const slide = pptx.addSlide();
    slide.addText(s.heading, { x: 0.5, y: 0.35, w: 9, fontSize: 24, bold: true, color: BRAND.primary });
    slide.addShape(pptx.ShapeType.rect, { x: 0.5, y: 0.95, w: 9, h: 0.05, fill: { color: BRAND.accent } });

    const bullets = [...s.bullets, ...s.paragraphs].slice(0, 8);
    if (bullets.length) {
      slide.addText(bullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })), {
        x: 0.6, y: 1.25, w: 8.8, h: 4.0, fontSize: 14, color: BRAND.ink, valign: "top",
      });
    }
    for (const t of s.tables.slice(0, 1)) {
      slide.addTable(
        [t.headers.map((h) => ({ text: h, options: { bold: true, color: "FFFFFF", fill: { color: BRAND.primary } } })),
          ...t.rows.slice(0, 10).map((r) => t.headers.map((_, ci) => ({ text: r[ci] ?? "" })))],
        { x: 0.5, y: bullets.length ? 3.6 : 1.3, w: 9, fontSize: 11, border: { pt: 0.5, color: "CBD5E1" } },
      );
    }
  }

  return (await pptx.write({ outputType: "blob" })) as Blob;
}

// ------------------------------------------------------------------- PDF
async function buildPdf(doc: ParsedDoc) {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const width = pdf.internal.pageSize.getWidth() - margin * 2;
  let y = margin;

  const nextPage = (needed = 40) => {
    if (y + needed > pdf.internal.pageSize.getHeight() - margin) { pdf.addPage(); y = margin; }
  };

  pdf.setFillColor(30, 58, 138);
  pdf.rect(0, 0, pdf.internal.pageSize.getWidth(), 70, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.text(doc.title.slice(0, 70), margin, 42);
  y = 100;
  pdf.setTextColor(71, 85, 105);
  pdf.setFontSize(9);
  pdf.text(`Generated by Amehnities AI · ${new Date().toLocaleString()}`, margin, y);
  y += 24;

  for (const s of doc.sections) {
    nextPage(60);
    pdf.setTextColor(30, 58, 138);
    pdf.setFontSize(13);
    pdf.text(s.heading, margin, y);
    y += 18;
    pdf.setTextColor(15, 23, 42);
    pdf.setFontSize(10);

    for (const p of s.paragraphs) {
      const lines = pdf.splitTextToSize(p, width) as string[];
      for (const l of lines) { nextPage(); pdf.text(l, margin, y); y += 14; }
      y += 4;
    }
    for (const b of s.bullets) {
      const lines = pdf.splitTextToSize(`• ${b}`, width - 10) as string[];
      for (const l of lines) { nextPage(); pdf.text(l, margin + 10, y); y += 14; }
    }
    for (const t of s.tables) {
      nextPage(30);
      pdf.setFontSize(9);
      pdf.setTextColor(30, 58, 138);
      pdf.text(t.headers.join("  |  "), margin, y); y += 13;
      pdf.setTextColor(15, 23, 42);
      for (const r of t.rows) {
        const line = t.headers.map((_, ci) => r[ci] ?? "").join("  |  ");
        for (const l of pdf.splitTextToSize(line, width) as string[]) { nextPage(); pdf.text(l, margin, y); y += 12; }
      }
      pdf.setFontSize(10);
      y += 8;
    }
    y += 8;
  }

  return pdf.output("blob") as Blob;
}

// ------------------------------------------------------------------ XLSX
async function buildXlsx(doc: ParsedDoc) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  let sheetCount = 0;

  doc.sections.forEach((s, si) => {
    s.tables.forEach((t, ti) => {
      const aoa = [t.headers, ...t.rows.map((r) => t.headers.map((_, ci) => r[ci] ?? ""))];
      const ws = XLSX.utils.aoa_to_sheet(aoa);
      ws["!cols"] = t.headers.map((h) => ({ wch: Math.min(40, Math.max(12, h.length + 4)) }));
      const name = `${s.heading || `Section ${si + 1}`}${ti ? ` ${ti + 1}` : ""}`.replace(/[\\/?*[\]:]/g, "").slice(0, 28) || `Sheet${++sheetCount}`;
      XLSX.utils.book_append_sheet(wb, ws, name);
      sheetCount++;
    });
  });

  if (!sheetCount) {
    const aoa = [["Section", "Content"]];
    doc.sections.forEach((s) => {
      [...s.paragraphs, ...s.bullets].forEach((p) => aoa.push([s.heading, p]));
    });
    const ws = XLSX.utils.aoa_to_sheet(aoa);
    ws["!cols"] = [{ wch: 28 }, { wch: 100 }];
    XLSX.utils.book_append_sheet(wb, ws, "Report");
  }

  const out = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  return new Blob([out], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
}

/** Convert an assistant Markdown answer into a downloadable deliverable. */
export async function generateDocument(markdown: string, format: DocFormat, titleHint?: string): Promise<string> {
  const doc = parseMarkdownDocument(markdown, titleHint);
  const blob =
    format === "docx" ? await buildDocx(doc)
    : format === "pptx" ? await buildPptx(doc)
    : format === "xlsx" ? await buildXlsx(doc)
    : await buildPdf(doc);

  const filename = safeName(doc.title, format);
  download(blob, filename);
  return filename;
}
